In [ ]:
!pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
# ONLY RUN THIS CELL IF USING GOOGLE COLAB

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [24]:
# Import packages
# Add more as needed
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PROBLEM 2

In [25]:
# Please specify the full paths to Q3 geno and pheno

geno_path_p2 = '/content/gdrive/MyDrive/C124/ps2_data/Q2_data/gwas.geno'
pheno_path_p2 = '/content/gdrive/MyDrive/C124/ps2_data/Q2_data/gwas.pheno'

In [26]:
# See Q2_data/README for information on these files
gwas_geno = pd.read_csv(geno_path_p2, header=None, sep=' ')
gwas_pheno = pd.read_csv(pheno_path_p2, header=None, sep=' ')

In [27]:
gwas_geno

,0,1,2,3,4,5,6,7,8,9,...,372,373,374,375,376,377,378,379,380,381
0,0,0,2,2,0,1,0,0,1,0,...,1,0,1,0,1,1,0,1,1,1
1,0,0,1,2,1,2,1,0,1,0,...,0,1,1,0,0,1,0,0,0,1
2,0,1,1,2,1,2,0,0,0,0,...,2,1,0,0,1,0,0,0,0,2
3,0,0,2,2,0,2,0,0,1,0,...,2,2,2,1,1,1,0,0,0,2
4,0,0,1,2,1,2,0,0,1,0,...,2,1,2,0,2,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0,0,2,1,1,2,0,0,2,0,...,1,1,0,0,0,2,0,0,0,1
496,1,0,1,2,0,1,0,1,1,1,...,2,1,2,0,0,1,0,0,0,1
497,0,0,1,2,0,2,0,0,1,0,...,2,2,2,0,0,0,0,0,0,1
498,1,0,2,2,1,1,0,0,2,0,...,2,1,2,0,1,1,0,0,0,1
499,1,1,2,1,2,2,0,0,2,0,...,1,2,2,0,0,2,1,0,0,2

In [28]:
gwas_pheno

            0         1         2           3
0   -0.325143  0.503856  1.732611    2.092371
1   -0.020982 -0.321068  2.452343 -431.129657
2   -0.371869 -0.216067  0.294997    0.594309
3   -1.477984 -2.209726  4.796187    0.330592
4    0.500458  1.464210  0.318061    0.491238
..        ...       ...       ...         ...
495 -0.229760 -1.379190  1.068351    0.086788
496 -0.511328  3.125155  1.592204    0.236867
497  0.214149  0.628176  0.111877    0.142040
498 -0.396145  0.420983 -0.489254   -0.092078
499  0.166658 -0.697764 -1.588209    1.999078

[500 rows x 4 columns]

In [13]:
# YOUR SOLUTION HERE

PROBLEM 3

In [14]:
# Please specify the full paths to Q3 training/test genos and phenos

geno_train_path_p3 = '/content/gdrive/MyDrive/C124/ps2_data/Q3_data/ridge.training.geno'
pheno_train_path_p3 = '/content/gdrive/MyDrive/C124/ps2_data/Q3_data/ridge.training.pheno'
geno_test_path_p3 = '/content/gdrive/MyDrive/C124/ps2_data/Q3_data/ridge.test.geno'
pheno_test_path_p3 = '/content/gdrive/MyDrive/C124/ps2_data/Q3_data/ridge.test.pheno'

In [17]:
# See Q3_data/README for information on these files
ridge_training_geno = pd.read_csv(geno_train_path_p3, header=None, sep=' ')
ridge_training_pheno = pd.read_csv(pheno_train_path_p3, header=None, sep=' ')
ridge_test_geno = pd.read_csv(geno_test_path_p3, header=None, sep=' ')
ridge_test_pheno = pd.read_csv(pheno_test_path_p3, header=None, sep=' ')

In [22]:
ridge_training_geno

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,2,2,1,2,2,1,2,0,1,1,...,1,1,1,0,2,2,1,2,1,2
1,0,2,0,1,1,1,0,0,1,2,...,1,1,0,0,0,1,1,2,2,0
2,2,1,2,0,0,1,0,1,2,1,...,2,2,0,1,0,0,1,1,1,2
3,2,0,0,2,2,2,1,1,2,0,...,1,1,1,1,2,0,1,2,0,2
4,1,2,2,1,0,2,0,1,2,2,...,2,0,0,1,2,2,0,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,2,0,1,1,2,0,1,1,2,2,...,0,0,1,0,0,0,2,1,2,0
896,2,1,2,2,2,2,1,1,0,1,...,2,1,0,0,2,2,1,2,1,2
897,1,0,1,2,0,1,2,0,0,1,...,2,0,1,0,0,1,1,2,1,1
898,1,1,1,0,2,2,0,1,1,2,...,0,0,0,2,0,1,2,0,2,0
899,1,0,1,2,2,2,2,1,0,1,...,1,2,2,2,2,0,2,2,0,0

In [23]:
ridge_training_pheno

           0
0    52.0499
1    35.5899
2    31.9954
3    43.0739
4    33.8418
..       ...
895  18.7085
896  29.4096
897  66.4829
898  67.1417
899  50.5079

[900 rows x 1 columns]

In [20]:
ridge_test_geno

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
0,1,1,2,1,2,0,0,0,2,1,...,0,1,1,0,2,2,1,1,1,1
1,2,0,0,2,1,0,1,1,1,0,...,0,1,0,1,1,0,1,1,0,1
2,2,1,1,0,0,2,2,0,1,1,...,0,0,0,0,0,0,0,2,2,1
3,0,1,2,1,1,0,0,0,0,2,...,1,0,0,0,1,1,2,0,0,1
4,2,2,1,0,0,1,0,0,2,2,...,2,2,0,0,2,0,1,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,2,2,2,1,1,2,0,1,...,0,0,1,1,0,2,2,1,0,0
96,1,0,0,1,2,2,1,0,2,1,...,2,0,1,1,0,1,1,2,1,2
97,1,2,1,2,1,2,2,0,2,1,...,1,1,1,2,0,1,1,1,1,2
98,0,1,2,0,0,2,1,0,1,0,...,1,1,0,2,2,2,1,0,1,0
99,1,1,1,0,0,2,1,0,1,1,...,2,0,1,1,1,2,1,2,1,2

In [21]:
ridge_test_pheno

          0
0    9.0483
1    6.4270
2  -11.5630
3   53.5267
4   58.6365
..      ...
95  29.5647
96  16.5643
97  34.8143
98  41.4503
99  47.3253

[100 rows x 1 columns]

In [29]:
# YOUR SOLUTION HERE